-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(100) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: Valor fecha y hora
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  --Borrado lógico - No se borra el registro físicamente
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_rol_UNIQUE` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB;

-- DIGO MUERE - DEBEMOS SACARLO DEL SISTEMA. BORRADO FÍSICO DELETE FROM USUARIO
-- CON DELETE EL DATOP DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LÓGICO (campo deleted activo - deleted 1)
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password_hash` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: Valor fecha y hora
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `roles_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`roles_id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: Valor fecha y hora
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP, --CURRENT_TIMESTAMP: Valor fecha y hora
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insert Datos en tablas 5 registros

USE sistema_mensajes;
INSERT INTO roles(nombre_rol, descripcion_rol)
VALUES("admin", "Control total"),
("usuario comun","Permisos administrador basicos"),
("invitado", "usuario temporal con permisos limitados");
INSERT INTO usuarios(nombre_usuario, password_hash, email, id_rol) VALUES 
("randyGlock","randyGlock123","randy@gmail.com",2),
("nqzk","jheimy123","jheimy@gmail.com",1),
("marck069","Marcelo321","marcelo@gmail.com",2),
("joaco67","Joaquin6767","joaquin@gmail.com",3);

SELECT * FROM roles;
SELECT * FROM usuarios;

INSERT INTO comentarios(contenido, created_by, id_usuario) VALUES 
("Hola este es el primer comentario", 1, 1),
("Hola soy jheimy y soy admin", 2, 2),
("Hola soy Marcelo", 3, 3);

SELECT * FROM comentarios; -- Comprobar si existen comentarios

INSERT INTO mensajes(contenido, created_by, emisor, receptor) VALUES 
("Hola Joaquin, como estas?", 1, 1, 4),
("Hola jheimy, pasame la tarea", 3, 3, 2),
("Oe Randy, vas a venir?", 2, 2, 1);

SELECT * FROM mensajes;

SELECT contenido, emisor, receptor
FROM mensajes
WHERE emisor = 2 OR receptor = 2;

-- MOSTRAR USUARIOS QUE ESTAN ACTIVOS (DELETED 0)
SELECT nombre_usuario, email, id_rol, deleted
FROM usuarios
WHERE deleted = 0;

-- BORRAR UNO O MAS USUARIOS
UPDATE usuarios
SET deleted = 1
WHERE id_usuario = 1 OR id_usuario = 3;
SELECT * FROM usuarios;

-- RECUPERAR USUARIO
UPDATE usuarios
SET deleted = 0
WHERE id_usuario = 1;
SELECT * FROM usuarios;

-- TAREA
-- MOSTRAR ROLES DE USUARIO (NOMBRE, DESCRIPCION)
SELECT * FROM roles;
-- ELIMINAR 2 ROLES DE USUARIO
UPDATE roles
SET deleted = 1
WHERE id_rol = 3 OR id_rol=2;
SELECT * FROM roles;
-- RECUPERAR 1 ROL DE USUARIO
UPDATE roles
SET deleted = 0
WHERE id_rol = 2;
SELECT * FROM roles;
